// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input va8c52d,
 input v59a8ce,
 input v2d619b,
 output ve84e39,
 output v870b4e,
 output vd4ad8f,
 output v5ad7ee,
 output [0:3] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = v2d619b;
 assign w1 = v59a8ce;
 assign w2 = va8c52d;
 assign vd4ad8f = w3;
 assign v5ad7ee = w4;
 assign v870b4e = w5;
 assign ve84e39 = w6;
 main_v58f295 v58f295 (
  .T2(w0),
  .T1(w1),
  .T0(w2),
  .U3_4(w3),
  .U7(w4),
  .U2_5(w5),
  .U1_6(w6)
 );
 assign vinit = 4'b0000;
endmodule

//---------------------------------------------------
//-- DECODER
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------

module main_v58f295 (
 input T0,
 input T1,
 input T2,
 output U1_6,
 output U2_5,
 output U3_4,
 output U7
);
 assign U1_6 = T2;
 assign U2_5 = T2 + T1;
 assign U3_4 = T2 & T1;
 assign U7 = T0;
endmodule
