// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input v8f4acb,
 input v654dbf,
 output v63b4e3,
 output vabdbe9,
 output v9651e7,
 output v8ef047,
 output v25c211,
 output [0:3] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 assign w3 = v654dbf;
 assign v8ef047 = w26;
 assign v9651e7 = w27;
 assign vabdbe9 = w28;
 assign v63b4e3 = w29;
 assign w31 = v8f4acb;
 assign v25c211 = w33;
 assign w9 = w8;
 assign w10 = w0;
 assign w14 = w13;
 assign w15 = w13;
 assign w15 = w14;
 assign w17 = w0;
 assign w17 = w10;
 assign w18 = w11;
 assign w19 = w12;
 assign w23 = w0;
 assign w23 = w10;
 assign w23 = w17;
 assign w24 = w11;
 assign w24 = w18;
 assign w25 = w12;
 assign w25 = w19;
 assign w30 = w11;
 assign w30 = w18;
 assign w30 = w24;
 assign w33 = w32;
 v74c286 v11795c (
  .v921d60(w4),
  .v53e727(w5),
  .v49c067(w6),
  .v66bbf1(w13),
  .vb772be(w14),
  .v26e436(w15),
  .v635938(w16),
  .v464cc6(w17),
  .v25b854(w18),
  .va4ae88(w19)
 );
 vb1c867 vf3d19a (
  .v289238(w0),
  .v1c95bf(w11),
  .vaa2332(w12),
  .vc38257(w20),
  .ve86d71(w21),
  .vead872(w22),
  .v3e83a1(w32)
 );
 v016822 v23fb24 (
  .v55292b(w1),
  .v71f37c(w2),
  .va00921(w4),
  .va83de4(w5),
  .v5331ef(w6),
  .vc117f6(w7),
  .v88c2ed(w8),
  .v1b565e(w9),
  .vcb28b3(w10),
  .vb07d28(w11),
  .va65bee(w12),
  .vf24815(w20),
  .va48b72(w21),
  .vd326c3(w22)
 );
 vd30ca9 vbfcd79 (
  .v9fb85f(w8)
 );
 vfebcfe v408121 (
  .v9fb85f(w7)
 );
 vfebcfe v6411bb (
  .v9fb85f(w16)
 );
 vd30ca9 v76bb62 (
  .v9fb85f(w13)
 );
 v70ad9d vaffaa5 (
  .vcd1bee(w0),
  .vb92af2(w1),
  .vdcb538(w2),
  .vd76755(w3),
  .v420011(w30)
 );
 va0ba8c vb1685c (
  .v2d619b(w23),
  .v59a8ce(w24),
  .va8c52d(w25),
  .v5ad7ee(w26),
  .vd4ad8f(w27),
  .v870b4e(w28),
  .ve84e39(w29)
 );
 v6a5074 vda18e0 (
  .v0daa9e(w31),
  .v2efea4(w32)
 );
 assign vinit = 4'b0000;
endmodule

//---- Top entity
module v74c286 (
 input v66bbf1,
 input v635938,
 input vb772be,
 input v26e436,
 input va4ae88,
 input v25b854,
 input v464cc6,
 output v921d60,
 output v53e727,
 output v49c067
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign w2 = v25b854;
 assign w3 = vb772be;
 assign w4 = va4ae88;
 assign w5 = v635938;
 assign w6 = v464cc6;
 assign w7 = v26e436;
 assign v53e727 = w8;
 assign v921d60 = w9;
 assign v49c067 = w10;
 assign w11 = v66bbf1;
 va4ba07 va26080 (
  .v194f88(w1),
  .v64d63b(w4),
  .v7966e4(w5),
  .v95e619(w9),
  .v380bca(w11)
 );
 va4ba07 v6125f9 (
  .v194f88(w0),
  .v380bca(w1),
  .v64d63b(w2),
  .v7966e4(w3),
  .v95e619(w8)
 );
 va4ba07 v313682 (
  .v380bca(w0),
  .v64d63b(w6),
  .v7966e4(w7),
  .v95e619(w10)
 );
endmodule

//---------------------------------------------------
//-- 3B ADDER
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module va4ba07 (
 input v7966e4,
 input v64d63b,
 input v380bca,
 output v95e619,
 output v194f88
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign w0 = v64d63b;
 assign w1 = v7966e4;
 assign w2 = v380bca;
 assign v95e619 = w4;
 assign w6 = v380bca;
 assign w9 = v7966e4;
 assign w10 = v64d63b;
 assign v194f88 = w11;
 assign w5 = w3;
 assign w6 = w2;
 assign w9 = w1;
 assign w10 = w0;
 v18c17a v49967d (
  .v3ca442(w0),
  .v0e28cb(w1),
  .vcbab45(w3)
 );
 v18c17a v811bf6 (
  .v3ca442(w2),
  .v0e28cb(w3),
  .vcbab45(w4)
 );
 vba518e vd8077b (
  .v0e28cb(w5),
  .v3ca442(w6),
  .vcbab45(w7)
 );
 vba518e vf4cff4 (
  .vcbab45(w8),
  .v0e28cb(w9),
  .v3ca442(w10)
 );
 v873425 v2053c6 (
  .v0e28cb(w7),
  .v3ca442(w8),
  .vcbab45(w11)
 );
endmodule

//---- Top entity
module v18c17a (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v18c17a_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: 2-bits input xor gate. Verilog implementation
//---------------------------------------------------

module v18c17a_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Two bits input And gate
//---------------------------------------------------

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR2: Two bits input OR gate
//---------------------------------------------------

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
//---- Top entity
module vb1c867 (
 input v3e83a1,
 input vead872,
 input ve86d71,
 input vc38257,
 output vaa2332,
 output v1c95bf,
 output v289238
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign w0 = v3e83a1;
 assign w1 = v3e83a1;
 assign w2 = v3e83a1;
 assign w3 = vead872;
 assign w4 = ve86d71;
 assign w5 = vc38257;
 assign v289238 = w6;
 assign v1c95bf = w7;
 assign vaa2332 = w8;
 assign w1 = w0;
 assign w2 = w0;
 assign w2 = w1;
 v58ed2b vcdc0e9 (
  .va4102a(w0),
  .vf54559(w3),
  .ve8318d(w8)
 );
 v58ed2b v60face (
  .va4102a(w1),
  .vf54559(w4),
  .ve8318d(w7)
 );
 v58ed2b v881c39 (
  .va4102a(w2),
  .vf54559(w5),
  .ve8318d(w6)
 );
endmodule

//---------------------------------------------------
//-- 3B REG
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module v58ed2b #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output va58c5b,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v58ed2b_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- sys-DFF-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- System - D Flip-flop. Capture data every system clock cycle. Verilog implementation
//---------------------------------------------------

module v58ed2b_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg qi = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   qi <= d;
   
 //-- Connect the register with the
 //-- output
 assign q = qi;
endmodule
//---- Top entity
module v016822 (
 input va00921,
 input va83de4,
 input v5331ef,
 input vc117f6,
 input v88c2ed,
 input v1b565e,
 input va65bee,
 input vb07d28,
 input vcb28b3,
 input v55292b,
 input v71f37c,
 output vd326c3,
 output va48b72,
 output vf24815
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w0 = va00921;
 assign w1 = va83de4;
 assign w2 = v5331ef;
 assign w3 = vc117f6;
 assign w4 = v88c2ed;
 assign w5 = v1b565e;
 assign w6 = vb07d28;
 assign w7 = vcb28b3;
 assign w8 = va65bee;
 assign w9 = v71f37c;
 assign w10 = v71f37c;
 assign w11 = v71f37c;
 assign w12 = v55292b;
 assign w13 = v55292b;
 assign w14 = v55292b;
 assign vd326c3 = w15;
 assign va48b72 = w16;
 assign vf24815 = w17;
 assign w10 = w9;
 assign w11 = w9;
 assign w11 = w10;
 assign w13 = w12;
 assign w14 = w12;
 assign w14 = w13;
 v22d161 v8768c4 (
  .vc574c7(w0),
  .vddbbcb(w3),
  .ve79f44(w8),
  .v5d7f47(w11),
  .v9ef2ab(w14),
  .vb07df5(w15)
 );
 v22d161 vbe0dd1 (
  .vc574c7(w1),
  .vddbbcb(w4),
  .ve79f44(w6),
  .v5d7f47(w10),
  .v9ef2ab(w13),
  .vb07df5(w16)
 );
 v22d161 v73ef4d (
  .vc574c7(w2),
  .vddbbcb(w5),
  .ve79f44(w7),
  .v5d7f47(w9),
  .v9ef2ab(w12),
  .vb07df5(w17)
 );
endmodule

//---------------------------------------------------
//-- 9:3 MUX
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module v22d161 (
 input vc574c7,
 input vddbbcb,
 input ve79f44,
 input v9ef2ab,
 input v5d7f47,
 output vb07df5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = vddbbcb;
 assign w1 = vc574c7;
 assign w3 = ve79f44;
 assign w4 = v9ef2ab;
 assign w5 = v5d7f47;
 assign vb07df5 = w6;
 vc1653f vf9b6b0 (
  .vd646f9(w0),
  .vfe17e9(w1),
  .v875293(w2),
  .ve50a7b(w4)
 );
 vc1653f vd2fa96 (
  .vfe17e9(w2),
  .vd646f9(w3),
  .ve50a7b(w5),
  .v875293(w6)
 );
endmodule

//---------------------------------------------------
//-- 3:1 MUX
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module vc1653f (
 input vd646f9,
 input vfe17e9,
 input ve50a7b,
 output v875293
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign v875293 = w0;
 assign w1 = ve50a7b;
 assign w2 = vfe17e9;
 assign w3 = vd646f9;
 vc1653f_v4d0636 v4d0636 (
  .o(w0),
  .sel(w1),
  .i0(w2),
  .i1(w3)
 );
endmodule

//---------------------------------------------------
//-- Mux-2-1-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2-to-1 Multplexer (1-bit channels). Verilog implementation
//---------------------------------------------------

module vc1653f_v4d0636 (
 input i1,
 input i0,
 input sel,
 output o
);
 //-- 2-to-1 Multiplexer 
 
 assign o = sel ? i1 : i0;
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 0
//---------------------------------------------------

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
//---- Top entity
module v70ad9d (
 input v420011,
 input vcd1bee,
 input vd76755,
 output vb92af2,
 output vdcb538
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = vcd1bee;
 assign w1 = v420011;
 assign w2 = vd76755;
 assign vdcb538 = w3;
 assign vb92af2 = w4;
 vba518e v59c6f4 (
  .v3ca442(w0),
  .v0e28cb(w1),
  .vcbab45(w4)
 );
 v3676a0 v8463ef (
  .v0e28cb(w2),
  .vcbab45(w3)
 );
endmodule

//---------------------------------------------------
//-- F
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT gate (Verilog implementation)
//---------------------------------------------------

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
//---- Top entity
module va0ba8c (
 input va8c52d,
 input v59a8ce,
 input v2d619b,
 output ve84e39,
 output v870b4e,
 output vd4ad8f,
 output v5ad7ee
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = v2d619b;
 assign w1 = v59a8ce;
 assign w2 = va8c52d;
 assign vd4ad8f = w3;
 assign v5ad7ee = w4;
 assign v870b4e = w5;
 assign ve84e39 = w6;
 va0ba8c_v58f295 v58f295 (
  .T2(w0),
  .T1(w1),
  .T0(w2),
  .U3_4(w3),
  .U7(w4),
  .U2_5(w5),
  .U1_6(w6)
 );
endmodule

//---------------------------------------------------
//-- DECODER
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------

module va0ba8c_v58f295 (
 input T0,
 input T1,
 input T2,
 output U1_6,
 output U2_5,
 output U3_4,
 output U7
);
 assign U1_6 = T2;
 assign U2_5 = T2 | T1;
 assign U3_4 = T2 & T1;
 assign U7 = T0;
endmodule
//---- Top entity
module v6a5074 #(
 parameter v100e1b = 20
) (
 input v0daa9e,
 output v2efea4
);
 localparam p2 = v100e1b;
 wire w0;
 wire w1;
 assign v2efea4 = w0;
 assign w1 = v0daa9e;
 v6a5074_vac7386 #(
  .N(p2)
 ) vac7386 (
  .clk_out(w0),
  .clk_in(w1)
 );
endmodule

//---------------------------------------------------
//-- PrescalerN
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Parametric N-bits prescaler
//---------------------------------------------------

module v6a5074_vac7386 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 //-- Number of bits of the prescaler
 //parameter N = 22;
 
 //-- divisor register
 reg [N-1:0] divcounter;
 
 //-- N bit counter
 always @(posedge clk_in)
   divcounter <= divcounter + 1;
 
 //-- Use the most significant bit as output
 assign clk_out = divcounter[N-1];
endmodule
