// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input v9d5dca,
 output v0d0ab2,
 output v9cc4b5,
 output vc2dd3d,
 output va794c0,
 output v53e3ab,
 output v99a925,
 output v6c11e9,
 output va99645,
 output v4e717a,
 output vf0c1b9,
 output vbd6639
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire w38;
 assign v53e3ab = w27;
 assign v99a925 = w28;
 assign v6c11e9 = w29;
 assign va99645 = w30;
 assign v4e717a = w31;
 assign vf0c1b9 = w32;
 assign vbd6639 = w33;
 assign va794c0 = w34;
 assign vc2dd3d = w35;
 assign v9cc4b5 = w36;
 assign v0d0ab2 = w37;
 assign w38 = v9d5dca;
 assign w12 = w0;
 assign w13 = w1;
 assign w14 = w2;
 assign w15 = w3;
 assign w17 = w16;
 assign w18 = w16;
 assign w18 = w17;
 assign w19 = w16;
 assign w19 = w17;
 assign w19 = w18;
 assign w22 = w21;
 assign w23 = w21;
 assign w23 = w22;
 assign w24 = w0;
 assign w24 = w12;
 assign w25 = w3;
 assign w25 = w15;
 assign w34 = w3;
 assign w34 = w15;
 assign w34 = w25;
 assign w35 = w2;
 assign w35 = w14;
 assign w36 = w1;
 assign w36 = w13;
 assign w37 = w0;
 assign w37 = w12;
 assign w37 = w24;
 v4b1310 va83da8 (
  .v7f95f1(w0),
  .vf1e05c(w1),
  .vad9429(w2),
  .v8e79c8(w3),
  .v75e576(w4),
  .v4562e2(w5),
  .v74ef36(w6),
  .vf859cf(w7),
  .v70acf6(w38)
 );
 v6e5670 v1b0279 (
  .v1ebd7b(w8),
  .v45a92f(w9),
  .ve24cc2(w10),
  .va0f749(w11),
  .v408a69(w12),
  .v373f06(w13),
  .v9a7e5d(w14),
  .v253577(w15),
  .vafcafd(w20),
  .v403810(w21),
  .v0d9aa9(w22),
  .v86b2d9(w23)
 );
 v360312 vb94544 (
  .ve9b7a5(w4),
  .v4fac57(w5),
  .v1ff22a(w6),
  .vee7cfa(w7),
  .vae2b0b(w8),
  .v4de926(w9),
  .v876669(w10),
  .v128bd2(w11),
  .vb1945a(w16),
  .v9bdf31(w17),
  .v870462(w18),
  .v402e43(w19),
  .v0d4798(w26)
 );
 v0c9f7d vd0ffac (
  .vb947fa(w0),
  .v107d58(w1),
  .v9318a0(w2),
  .vc6a4b2(w3),
  .v1f6e78(w27),
  .v335112(w28),
  .v8f6525(w29),
  .v3a8bb3(w30),
  .vcd0c16(w31),
  .v904cde(w32),
  .vcdb46b(w33)
 );
 vfebcfe vd79700 (
  .v9fb85f(w20)
 );
 vd30ca9 vc70039 (
  .v9fb85f(w21)
 );
 vd30ca9 v57ca82 (
  .v9fb85f(w16)
 );
 vba518e v53ef76 (
  .v0e28cb(w24),
  .v3ca442(w25),
  .vcbab45(w26)
 );
endmodule

//---- Top entity
module v4b1310 (
 input v70acf6,
 input v75e576,
 input v4562e2,
 input v74ef36,
 input vf859cf,
 output v7f95f1,
 output vf1e05c,
 output vad9429,
 output v8e79c8
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign w0 = v70acf6;
 assign w1 = v70acf6;
 assign w2 = v70acf6;
 assign w3 = v70acf6;
 assign w4 = v75e576;
 assign w5 = v4562e2;
 assign w6 = v74ef36;
 assign w7 = vf859cf;
 assign v8e79c8 = w8;
 assign vad9429 = w9;
 assign vf1e05c = w10;
 assign v7f95f1 = w11;
 assign w1 = w0;
 assign w2 = w0;
 assign w2 = w1;
 assign w3 = w0;
 assign w3 = w1;
 assign w3 = w2;
 v58ed2b v8e8e06 (
  .va4102a(w0),
  .vf54559(w4),
  .ve8318d(w11)
 );
 v58ed2b v2170e0 (
  .va4102a(w1),
  .vf54559(w5),
  .ve8318d(w10)
 );
 v58ed2b vf5c828 (
  .va4102a(w2),
  .vf54559(w6),
  .ve8318d(w9)
 );
 v58ed2b v089c1e (
  .va4102a(w3),
  .vf54559(w7),
  .ve8318d(w8)
 );
endmodule

//---- Top entity
module v58ed2b #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output va58c5b,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v58ed2b_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- sys-DFF-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- System - D Flip-flop. Capture data every system clock cycle. Verilog implementation
//---------------------------------------------------

module v58ed2b_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg qi = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   qi <= d;
   
 //-- Connect the register with the
 //-- output
 assign q = qi;
endmodule
//---- Top entity
module v6e5670 (
 input vcc364b,
 input vafcafd,
 input v403810,
 input v0d9aa9,
 input v86b2d9,
 input v408a69,
 input v373f06,
 input v9a7e5d,
 input v253577,
 output v1ebd7b,
 output v45a92f,
 output ve24cc2,
 output va0f749,
 output vdcbca8
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 assign w3 = v86b2d9;
 assign w4 = v0d9aa9;
 assign w5 = v403810;
 assign w6 = vafcafd;
 assign w7 = v408a69;
 assign w8 = v253577;
 assign w9 = v9a7e5d;
 assign w10 = v373f06;
 assign va0f749 = w11;
 assign ve24cc2 = w12;
 assign v45a92f = w13;
 assign v1ebd7b = w14;
 assign w15 = vcc364b;
 assign vdcbca8 = w16;
 va4ba07 v6c9028 (
  .v194f88(w2),
  .v7966e4(w6),
  .v64d63b(w7),
  .v95e619(w14),
  .v380bca(w15)
 );
 va4ba07 v46b543 (
  .v194f88(w1),
  .v380bca(w2),
  .v7966e4(w5),
  .v64d63b(w10),
  .v95e619(w13)
 );
 va4ba07 vb46875 (
  .v194f88(w0),
  .v380bca(w1),
  .v7966e4(w4),
  .v64d63b(w9),
  .v95e619(w12)
 );
 va4ba07 v580bd4 (
  .v380bca(w0),
  .v7966e4(w3),
  .v64d63b(w8),
  .v95e619(w11),
  .v194f88(w16)
 );
endmodule

//---- Top entity
module va4ba07 (
 input v7966e4,
 input v64d63b,
 input v380bca,
 output v95e619,
 output v194f88
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign w0 = v64d63b;
 assign w1 = v7966e4;
 assign w2 = v380bca;
 assign v95e619 = w4;
 assign w6 = v380bca;
 assign w9 = v7966e4;
 assign w10 = v64d63b;
 assign v194f88 = w11;
 assign w5 = w3;
 assign w6 = w2;
 assign w9 = w1;
 assign w10 = w0;
 v18c17a v49967d (
  .v3ca442(w0),
  .v0e28cb(w1),
  .vcbab45(w3)
 );
 v18c17a v811bf6 (
  .v3ca442(w2),
  .v0e28cb(w3),
  .vcbab45(w4)
 );
 vba518e vd8077b (
  .v0e28cb(w5),
  .v3ca442(w6),
  .vcbab45(w7)
 );
 vba518e vf4cff4 (
  .vcbab45(w8),
  .v0e28cb(w9),
  .v3ca442(w10)
 );
 v873425 v2053c6 (
  .v0e28cb(w7),
  .v3ca442(w8),
  .vcbab45(w11)
 );
endmodule

//---- Top entity
module v18c17a (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v18c17a_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: 2-bits input xor gate. Verilog implementation
//---------------------------------------------------

module v18c17a_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Two bits input And gate
//---------------------------------------------------

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR2: Two bits input OR gate
//---------------------------------------------------

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
//---- Top entity
module v360312 (
 input vb1945a,
 input v9bdf31,
 input v870462,
 input v402e43,
 input vae2b0b,
 input v4de926,
 input v876669,
 input v128bd2,
 input v0d4798,
 output ve9b7a5,
 output v4fac57,
 output v1ff22a,
 output vee7cfa
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 assign vee7cfa = w0;
 assign v1ff22a = w1;
 assign v4fac57 = w2;
 assign ve9b7a5 = w3;
 assign w4 = v128bd2;
 assign w5 = v876669;
 assign w6 = v4de926;
 assign w7 = vae2b0b;
 assign w8 = v0d4798;
 assign w9 = v0d4798;
 assign w10 = v0d4798;
 assign w11 = v0d4798;
 assign w12 = vb1945a;
 assign w13 = v402e43;
 assign w14 = v870462;
 assign w15 = v9bdf31;
 assign w9 = w8;
 assign w10 = w8;
 assign w10 = w9;
 assign w11 = w8;
 assign w11 = w9;
 assign w11 = w10;
 vc1653f v01218b (
  .v875293(w3),
  .vfe17e9(w7),
  .ve50a7b(w11),
  .vd646f9(w12)
 );
 vc1653f v19dfe9 (
  .v875293(w2),
  .vfe17e9(w6),
  .ve50a7b(w10),
  .vd646f9(w15)
 );
 vc1653f v2e743e (
  .v875293(w1),
  .vfe17e9(w5),
  .ve50a7b(w9),
  .vd646f9(w14)
 );
 vc1653f v8f9d88 (
  .v875293(w0),
  .vfe17e9(w4),
  .ve50a7b(w8),
  .vd646f9(w13)
 );
endmodule

//---- Top entity
module vc1653f (
 input vd646f9,
 input vfe17e9,
 input ve50a7b,
 output v875293
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign v875293 = w0;
 assign w1 = ve50a7b;
 assign w2 = vfe17e9;
 assign w3 = vd646f9;
 vc1653f_v4d0636 v4d0636 (
  .o(w0),
  .sel(w1),
  .i0(w2),
  .i1(w3)
 );
endmodule

//---------------------------------------------------
//-- Mux-2-1-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2-to-1 Multplexer (1-bit channels). Verilog implementation
//---------------------------------------------------

module vc1653f_v4d0636 (
 input i1,
 input i0,
 input sel,
 output o
);
 //-- 2-to-1 Multiplexer 
 
 assign o = sel ? i1 : i0;
endmodule
//---- Top entity
module v0c9f7d (
 input vb947fa,
 input v107d58,
 input v9318a0,
 input vc6a4b2,
 output v1f6e78,
 output v335112,
 output v8f6525,
 output v3a8bb3,
 output vcd0c16,
 output v904cde,
 output vcdb46b
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire w38;
 wire w39;
 wire w40;
 wire w41;
 wire w42;
 wire w43;
 wire w44;
 wire w45;
 wire w46;
 wire w47;
 wire w48;
 wire w49;
 wire w50;
 wire w51;
 wire w52;
 wire w53;
 wire w54;
 wire w55;
 wire w56;
 wire w57;
 wire w58;
 wire w59;
 wire w60;
 wire w61;
 wire w62;
 wire w63;
 wire w64;
 wire w65;
 wire w66;
 wire w67;
 wire w68;
 wire w69;
 wire w70;
 wire w71;
 wire w72;
 wire w73;
 wire w74;
 wire w75;
 wire w76;
 wire w77;
 wire w78;
 wire w79;
 wire w80;
 wire w81;
 wire w82;
 wire w83;
 wire w84;
 wire w85;
 wire w86;
 wire w87;
 wire w88;
 wire w89;
 wire w90;
 wire w91;
 wire w92;
 wire w93;
 wire w94;
 wire w95;
 wire w96;
 wire w97;
 wire w98;
 wire w99;
 wire w100;
 wire w101;
 wire w102;
 wire w103;
 wire w104;
 assign w0 = vb947fa;
 assign w1 = v107d58;
 assign w2 = v9318a0;
 assign w3 = vc6a4b2;
 assign w7 = vb947fa;
 assign w8 = v9318a0;
 assign v1f6e78 = w14;
 assign w17 = vb947fa;
 assign w18 = v9318a0;
 assign w21 = v107d58;
 assign w22 = v9318a0;
 assign v335112 = w23;
 assign w29 = v107d58;
 assign v8f6525 = w30;
 assign w34 = vb947fa;
 assign w35 = v9318a0;
 assign w40 = v9318a0;
 assign w41 = v107d58;
 assign w42 = vb947fa;
 assign w46 = vc6a4b2;
 assign w47 = v9318a0;
 assign w48 = v107d58;
 assign w49 = vb947fa;
 assign w51 = vb947fa;
 assign w52 = v9318a0;
 assign w53 = vc6a4b2;
 assign w56 = vb947fa;
 assign w57 = vc6a4b2;
 assign w59 = v9318a0;
 assign w60 = v107d58;
 assign w61 = vb947fa;
 assign v3a8bb3 = w66;
 assign vcd0c16 = w67;
 assign w69 = v9318a0;
 assign w70 = v107d58;
 assign w71 = vb947fa;
 assign w77 = vb947fa;
 assign w82 = v9318a0;
 assign w83 = vb947fa;
 assign vcdb46b = w87;
 assign w88 = vb947fa;
 assign w94 = v107d58;
 assign w97 = v107d58;
 assign w98 = vb947fa;
 assign v904cde = w102;
 assign w103 = v107d58;
 assign w7 = w0;
 assign w8 = w2;
 assign w9 = w4;
 assign w10 = w6;
 assign w15 = w4;
 assign w15 = w9;
 assign w16 = w6;
 assign w16 = w10;
 assign w17 = w0;
 assign w17 = w7;
 assign w18 = w2;
 assign w18 = w8;
 assign w19 = w4;
 assign w19 = w9;
 assign w19 = w15;
 assign w20 = w11;
 assign w21 = w1;
 assign w22 = w2;
 assign w22 = w8;
 assign w22 = w18;
 assign w26 = w4;
 assign w26 = w9;
 assign w26 = w15;
 assign w26 = w19;
 assign w27 = w5;
 assign w28 = w11;
 assign w28 = w20;
 assign w29 = w1;
 assign w29 = w21;
 assign w31 = w4;
 assign w31 = w9;
 assign w31 = w15;
 assign w31 = w19;
 assign w31 = w26;
 assign w32 = w5;
 assign w32 = w27;
 assign w33 = w6;
 assign w33 = w10;
 assign w33 = w16;
 assign w34 = w0;
 assign w34 = w7;
 assign w34 = w17;
 assign w35 = w2;
 assign w35 = w8;
 assign w35 = w18;
 assign w35 = w22;
 assign w36 = w4;
 assign w36 = w9;
 assign w36 = w15;
 assign w36 = w19;
 assign w36 = w26;
 assign w36 = w31;
 assign w37 = w6;
 assign w37 = w10;
 assign w37 = w16;
 assign w37 = w33;
 assign w38 = w11;
 assign w38 = w20;
 assign w38 = w28;
 assign w39 = w4;
 assign w39 = w9;
 assign w39 = w15;
 assign w39 = w19;
 assign w39 = w26;
 assign w39 = w31;
 assign w39 = w36;
 assign w40 = w2;
 assign w40 = w8;
 assign w40 = w18;
 assign w40 = w22;
 assign w40 = w35;
 assign w41 = w1;
 assign w41 = w21;
 assign w41 = w29;
 assign w42 = w0;
 assign w42 = w7;
 assign w42 = w17;
 assign w42 = w34;
 assign w46 = w3;
 assign w47 = w2;
 assign w47 = w8;
 assign w47 = w18;
 assign w47 = w22;
 assign w47 = w35;
 assign w47 = w40;
 assign w48 = w1;
 assign w48 = w21;
 assign w48 = w29;
 assign w48 = w41;
 assign w49 = w0;
 assign w49 = w7;
 assign w49 = w17;
 assign w49 = w34;
 assign w49 = w42;
 assign w50 = w6;
 assign w50 = w10;
 assign w50 = w16;
 assign w50 = w33;
 assign w50 = w37;
 assign w51 = w0;
 assign w51 = w7;
 assign w51 = w17;
 assign w51 = w34;
 assign w51 = w42;
 assign w51 = w49;
 assign w52 = w2;
 assign w52 = w8;
 assign w52 = w18;
 assign w52 = w22;
 assign w52 = w35;
 assign w52 = w40;
 assign w52 = w47;
 assign w53 = w3;
 assign w53 = w46;
 assign w54 = w5;
 assign w54 = w27;
 assign w54 = w32;
 assign w55 = w6;
 assign w55 = w10;
 assign w55 = w16;
 assign w55 = w33;
 assign w55 = w37;
 assign w55 = w50;
 assign w56 = w0;
 assign w56 = w7;
 assign w56 = w17;
 assign w56 = w34;
 assign w56 = w42;
 assign w56 = w49;
 assign w56 = w51;
 assign w57 = w3;
 assign w57 = w46;
 assign w57 = w53;
 assign w58 = w4;
 assign w58 = w9;
 assign w58 = w15;
 assign w58 = w19;
 assign w58 = w26;
 assign w58 = w31;
 assign w58 = w36;
 assign w58 = w39;
 assign w59 = w2;
 assign w59 = w8;
 assign w59 = w18;
 assign w59 = w22;
 assign w59 = w35;
 assign w59 = w40;
 assign w59 = w47;
 assign w59 = w52;
 assign w60 = w1;
 assign w60 = w21;
 assign w60 = w29;
 assign w60 = w41;
 assign w60 = w48;
 assign w61 = w0;
 assign w61 = w7;
 assign w61 = w17;
 assign w61 = w34;
 assign w61 = w42;
 assign w61 = w49;
 assign w61 = w51;
 assign w61 = w56;
 assign w68 = w4;
 assign w68 = w9;
 assign w68 = w15;
 assign w68 = w19;
 assign w68 = w26;
 assign w68 = w31;
 assign w68 = w36;
 assign w68 = w39;
 assign w68 = w58;
 assign w69 = w2;
 assign w69 = w8;
 assign w69 = w18;
 assign w69 = w22;
 assign w69 = w35;
 assign w69 = w40;
 assign w69 = w47;
 assign w69 = w52;
 assign w69 = w59;
 assign w70 = w1;
 assign w70 = w21;
 assign w70 = w29;
 assign w70 = w41;
 assign w70 = w48;
 assign w70 = w60;
 assign w71 = w0;
 assign w71 = w7;
 assign w71 = w17;
 assign w71 = w34;
 assign w71 = w42;
 assign w71 = w49;
 assign w71 = w51;
 assign w71 = w56;
 assign w71 = w61;
 assign w73 = w4;
 assign w73 = w9;
 assign w73 = w15;
 assign w73 = w19;
 assign w73 = w26;
 assign w73 = w31;
 assign w73 = w36;
 assign w73 = w39;
 assign w73 = w58;
 assign w73 = w68;
 assign w74 = w5;
 assign w74 = w27;
 assign w74 = w32;
 assign w74 = w54;
 assign w75 = w6;
 assign w75 = w10;
 assign w75 = w16;
 assign w75 = w33;
 assign w75 = w37;
 assign w75 = w50;
 assign w75 = w55;
 assign w76 = w11;
 assign w76 = w20;
 assign w76 = w28;
 assign w76 = w38;
 assign w77 = w0;
 assign w77 = w7;
 assign w77 = w17;
 assign w77 = w34;
 assign w77 = w42;
 assign w77 = w49;
 assign w77 = w51;
 assign w77 = w56;
 assign w77 = w61;
 assign w77 = w71;
 assign w78 = w6;
 assign w78 = w10;
 assign w78 = w16;
 assign w78 = w33;
 assign w78 = w37;
 assign w78 = w50;
 assign w78 = w55;
 assign w78 = w75;
 assign w79 = w5;
 assign w79 = w27;
 assign w79 = w32;
 assign w79 = w54;
 assign w79 = w74;
 assign w80 = w4;
 assign w80 = w9;
 assign w80 = w15;
 assign w80 = w19;
 assign w80 = w26;
 assign w80 = w31;
 assign w80 = w36;
 assign w80 = w39;
 assign w80 = w58;
 assign w80 = w68;
 assign w80 = w73;
 assign w81 = w4;
 assign w81 = w9;
 assign w81 = w15;
 assign w81 = w19;
 assign w81 = w26;
 assign w81 = w31;
 assign w81 = w36;
 assign w81 = w39;
 assign w81 = w58;
 assign w81 = w68;
 assign w81 = w73;
 assign w81 = w80;
 assign w82 = w2;
 assign w82 = w8;
 assign w82 = w18;
 assign w82 = w22;
 assign w82 = w35;
 assign w82 = w40;
 assign w82 = w47;
 assign w82 = w52;
 assign w82 = w59;
 assign w82 = w69;
 assign w83 = w0;
 assign w83 = w7;
 assign w83 = w17;
 assign w83 = w34;
 assign w83 = w42;
 assign w83 = w49;
 assign w83 = w51;
 assign w83 = w56;
 assign w83 = w61;
 assign w83 = w71;
 assign w83 = w77;
 assign w88 = w0;
 assign w88 = w7;
 assign w88 = w17;
 assign w88 = w34;
 assign w88 = w42;
 assign w88 = w49;
 assign w88 = w51;
 assign w88 = w56;
 assign w88 = w61;
 assign w88 = w71;
 assign w88 = w77;
 assign w88 = w83;
 assign w89 = w6;
 assign w89 = w10;
 assign w89 = w16;
 assign w89 = w33;
 assign w89 = w37;
 assign w89 = w50;
 assign w89 = w55;
 assign w89 = w75;
 assign w89 = w78;
 assign w90 = w5;
 assign w90 = w27;
 assign w90 = w32;
 assign w90 = w54;
 assign w90 = w74;
 assign w90 = w79;
 assign w91 = w4;
 assign w91 = w9;
 assign w91 = w15;
 assign w91 = w19;
 assign w91 = w26;
 assign w91 = w31;
 assign w91 = w36;
 assign w91 = w39;
 assign w91 = w58;
 assign w91 = w68;
 assign w91 = w73;
 assign w91 = w80;
 assign w91 = w81;
 assign w92 = w4;
 assign w92 = w9;
 assign w92 = w15;
 assign w92 = w19;
 assign w92 = w26;
 assign w92 = w31;
 assign w92 = w36;
 assign w92 = w39;
 assign w92 = w58;
 assign w92 = w68;
 assign w92 = w73;
 assign w92 = w80;
 assign w92 = w81;
 assign w92 = w91;
 assign w93 = w5;
 assign w93 = w27;
 assign w93 = w32;
 assign w93 = w54;
 assign w93 = w74;
 assign w93 = w79;
 assign w93 = w90;
 assign w94 = w1;
 assign w94 = w21;
 assign w94 = w29;
 assign w94 = w41;
 assign w94 = w48;
 assign w94 = w60;
 assign w94 = w70;
 assign w95 = w4;
 assign w95 = w9;
 assign w95 = w15;
 assign w95 = w19;
 assign w95 = w26;
 assign w95 = w31;
 assign w95 = w36;
 assign w95 = w39;
 assign w95 = w58;
 assign w95 = w68;
 assign w95 = w73;
 assign w95 = w80;
 assign w95 = w81;
 assign w95 = w91;
 assign w95 = w92;
 assign w96 = w5;
 assign w96 = w27;
 assign w96 = w32;
 assign w96 = w54;
 assign w96 = w74;
 assign w96 = w79;
 assign w96 = w90;
 assign w96 = w93;
 assign w97 = w1;
 assign w97 = w21;
 assign w97 = w29;
 assign w97 = w41;
 assign w97 = w48;
 assign w97 = w60;
 assign w97 = w70;
 assign w97 = w94;
 assign w98 = w0;
 assign w98 = w7;
 assign w98 = w17;
 assign w98 = w34;
 assign w98 = w42;
 assign w98 = w49;
 assign w98 = w51;
 assign w98 = w56;
 assign w98 = w61;
 assign w98 = w71;
 assign w98 = w77;
 assign w98 = w83;
 assign w98 = w88;
 assign w103 = w1;
 assign w103 = w21;
 assign w103 = w29;
 assign w103 = w41;
 assign w103 = w48;
 assign w103 = w60;
 assign w103 = w70;
 assign w103 = w94;
 assign w103 = w97;
 assign w104 = w11;
 assign w104 = w20;
 assign w104 = w28;
 assign w104 = w38;
 assign w104 = w76;
 v96f098 vd3c5d6 (
  .v0e28cb(w0),
  .vcbab45(w11)
 );
 v96f098 vc89064 (
  .v0e28cb(w1),
  .vcbab45(w6)
 );
 v96f098 v98c1fb (
  .v0e28cb(w3),
  .vcbab45(w4)
 );
 v96f098 v830078 (
  .v0e28cb(w2),
  .vcbab45(w5)
 );
 v1497fd v0b0054 (
  .v4160b9(w4),
  .v237134(w5),
  .ve7be79(w6),
  .ve79e01(w7),
  .vd9653f(w12)
 );
 v1497fd v9682e6 (
  .v237134(w8),
  .v4160b9(w9),
  .ve7be79(w10),
  .ve79e01(w11),
  .vd9653f(w13)
 );
 v528969 va42833 (
  .v0e28cb(w12),
  .v3ca442(w13),
  .vcbab45(w14)
 );
 v1497fd v622dba (
  .v4160b9(w15),
  .ve7be79(w16),
  .ve79e01(w17),
  .v237134(w18),
  .vd9653f(w24)
 );
 v1497fd v59d3a8 (
  .v4160b9(w19),
  .ve79e01(w20),
  .ve7be79(w21),
  .v237134(w22),
  .vd9653f(w25)
 );
 v528969 v20daee (
  .vcbab45(w23),
  .v0e28cb(w24),
  .v3ca442(w25)
 );
 v1497fd v2b8f30 (
  .v4160b9(w26),
  .v237134(w27),
  .ve79e01(w28),
  .ve7be79(w29),
  .vd9653f(w30)
 );
 v1497fd vb6d448 (
  .v4160b9(w31),
  .v237134(w32),
  .ve7be79(w33),
  .ve79e01(w34),
  .vd9653f(w43)
 );
 v1497fd v18bdc5 (
  .v237134(w35),
  .v4160b9(w36),
  .ve7be79(w37),
  .ve79e01(w38),
  .vd9653f(w44)
 );
 v1497fd v407257 (
  .v4160b9(w39),
  .v237134(w40),
  .ve7be79(w41),
  .ve79e01(w42),
  .vd9653f(w45)
 );
 vffd5f9 ve0006b (
  .v8f8e2b(w43),
  .vc915bd(w44),
  .vc6fcc7(w45),
  .vc10598(w66)
 );
 vd7bcfb v8fc738 (
  .v6289ac(w46),
  .vfb1d45(w47),
  .vd12155(w48),
  .vde62da(w49),
  .v315b56(w62)
 );
 vd7bcfb v14a6a1 (
  .vd12155(w50),
  .vde62da(w51),
  .vfb1d45(w52),
  .v6289ac(w53),
  .v315b56(w63)
 );
 vd7bcfb v51dfc5 (
  .vfb1d45(w54),
  .vd12155(w55),
  .vde62da(w56),
  .v6289ac(w57),
  .v315b56(w64)
 );
 vd7bcfb v695b84 (
  .v6289ac(w58),
  .vfb1d45(w59),
  .vd12155(w60),
  .vde62da(w61),
  .v315b56(w65)
 );
 v1497fd v704c25 (
  .ve79e01(w62),
  .ve7be79(w63),
  .v237134(w64),
  .v4160b9(w65),
  .vd9653f(w67)
 );
 v1497fd v3349f2 (
  .v4160b9(w68),
  .v237134(w69),
  .ve7be79(w70),
  .ve79e01(w71),
  .vd9653f(w72)
 );
 vd7bcfb v1bbed1 (
  .v6289ac(w72),
  .vde62da(w99),
  .vd12155(w100),
  .vfb1d45(w101),
  .v315b56(w102)
 );
 v1497fd va469bf (
  .v4160b9(w73),
  .v237134(w74),
  .ve7be79(w75),
  .ve79e01(w76),
  .vd9653f(w84)
 );
 v1497fd v15f976 (
  .ve79e01(w77),
  .ve7be79(w78),
  .v237134(w79),
  .v4160b9(w80),
  .vd9653f(w85)
 );
 v1497fd ve3024c (
  .v4160b9(w81),
  .v237134(w82),
  .ve79e01(w83),
  .vd9653f(w86),
  .ve7be79(w103)
 );
 vffd5f9 v4cfcc2 (
  .v8f8e2b(w84),
  .vc915bd(w85),
  .vc6fcc7(w86),
  .vc10598(w87)
 );
 v1497fd v2e76ef (
  .ve79e01(w88),
  .ve7be79(w89),
  .v237134(w90),
  .v4160b9(w91),
  .vd9653f(w99)
 );
 v1497fd vba170e (
  .v4160b9(w92),
  .v237134(w93),
  .ve7be79(w94),
  .vd9653f(w100),
  .ve79e01(w104)
 );
 v1497fd vc8f88f (
  .v4160b9(w95),
  .v237134(w96),
  .ve7be79(w97),
  .ve79e01(w98),
  .vd9653f(w101)
 );
endmodule

//---------------------------------------------------
//-- 7-segment display decoder
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Decoder for a 7-segment display. Able to show values from 0-9.
//---------------------------------------------------
//---- Top entity
module v96f098 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v96f098_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT logic gate
//---------------------------------------------------

module v96f098_vd54ca1 (
 input a,
 output c
);
 // NOT logic gate
 
 assign c = ~ a;
endmodule
//---- Top entity
module v1497fd (
 input ve79e01,
 input ve7be79,
 input v237134,
 input v4160b9,
 output vd9653f
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = ve79e01;
 assign w1 = ve7be79;
 assign w3 = v237134;
 assign w5 = v4160b9;
 assign vd9653f = w6;
 v7ebc90 vc51eba (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w2)
 );
 v7ebc90 v8bd5c2 (
  .v0e28cb(w2),
  .v3ca442(w3),
  .vcbab45(w4)
 );
 v7ebc90 v713504 (
  .v0e28cb(w4),
  .v3ca442(w5),
  .vcbab45(w6)
 );
endmodule

//---------------------------------------------------
//-- AND gate
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module v7ebc90 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v7ebc90_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AND logic gate
//---------------------------------------------------

module v7ebc90_vf4938a (
 input a,
 input b,
 output c
);
 // AND logic gate
 
 assign c = a & b;
endmodule
//---- Top entity
module v528969 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v528969_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR logic gate
//---------------------------------------------------

module v528969_vf4938a (
 input a,
 input b,
 output c
);
 // OR logic gate
 
 assign c = a | b;
endmodule
//---- Top entity
module vffd5f9 (
 input v8f8e2b,
 input vc915bd,
 input vc6fcc7,
 output vc10598
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w1 = v8f8e2b;
 assign w2 = vc915bd;
 assign w3 = vc6fcc7;
 assign vc10598 = w4;
 v528969 ve420e8 (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w2)
 );
 v528969 v2f3070 (
  .v0e28cb(w0),
  .v3ca442(w3),
  .vcbab45(w4)
 );
endmodule

//---------------------------------------------------
//-- OR gate
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module vd7bcfb (
 input vde62da,
 input vd12155,
 input vfb1d45,
 input v6289ac,
 output v315b56
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = vde62da;
 assign w1 = vd12155;
 assign w3 = vfb1d45;
 assign w5 = v6289ac;
 assign v315b56 = w6;
 v528969 v1a8dae (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w2)
 );
 v528969 v3532d9 (
  .v0e28cb(w2),
  .v3ca442(w3),
  .vcbab45(w4)
 );
 v528969 v79b2d8 (
  .v0e28cb(w4),
  .v3ca442(w5),
  .vcbab45(w6)
 );
endmodule

//---------------------------------------------------
//-- OR gate
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 0
//---------------------------------------------------

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
